apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodyme-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: foodyme.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foodyme-service
            port:
              number: 80
